---
chestitems:
- - 261
  - 0
  - 1
- - 262
  - 0
  - 2
- - 262
  - 0
  - 3
- - 267
  - 0
  - 1
- - 268
  - 0
  - 1
- - 272
  - 0
  - 1
- - 276
  - 0
  - 1
- - 283
  - 0
  - 1
#If ON, then on player death, lightning will strike the ground where they died
#If OFF, then no lightning
lightning_effect: ON
...
