name: SurvivalGames
main: SurvivalGames\SurvivalGames
version: 4.0
api: 2.0.0
authors: EpicSteve33, ImagicalGamer & RedEnder


commands:
    sg:
        usage: /sg make
        description: SurvivalGames-Commands
    setrank:
        usage: /setrank
        description: SetRank-Command
    ranks:
        usage: /ranks
        description: Rank-Command
