name: SurvivalGames
main: SurvivalGames\SurvivalGames
version: 3.0.5
api: 
- 1.0.0
- 1.1.0
- 2.0.0
authors: EpicSteve33, ImagicalGamer & RedEnder


commands:
    sg:
        usage: /sg make
        description: SurvivalGames-Commands
    setrank:
        usage: /setrank
        description: Rank-Commands
